# Generated by Django 5.0 on 2025-10-09 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_enheadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eheadline',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='enheadline',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='headline',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lheadline',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pheadline',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sheadline',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='eheadline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eheadline',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enheadline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enheadline',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='headline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='headline',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lheadline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lheadline',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pheadline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pheadline',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheadline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sheadline',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
